### ISSUE TITLE
feature request set exact_match from command-line argument

### ISSUE THREAD

**Issue by N0rbert** [anenasa/pyppasearch#3]
I'm using your great script in daily basis. Thank you! 
And I found myself changing source code line

https://github.com/anenasa/pyppasearch/blob/main/pyppasearch.py#L17

from `exact_match=True` to `exact_match=False` depending on the current use-case.

If possible, please set `exact_match=True` as default, and allow user to set `False` from command-line argument.

**Comment by anenasa** [comment]
Fixed in https://github.com/anenasa/pyppasearch/commit/68601d300a22aebe0e19a44a38aa430b5f7bfc82.

**Comment by anenasa** [comment]
I added argument `--noexact`, you can use this to have `exact_match=False`.
